"""
VideoForge — Module 01c: Image Planner (Art Director pass).

Reads script.json after script generation (step 1), finds all __MARKER__ sentinels
in image_prompts, and replaces them with high-quality structured image prompts
generated by a dedicated Art Director LLM call.

The Art Director sees the FULL script narration before writing a single prompt —
enabling visual arc planning, uniqueness enforcement, and narration-locked descriptions.

Features:
- Sees entire video before placing first prompt (no inline tunnel vision)
- Structured prompt formula: subject + emotion + lighting + composition + style
- Visual arc: opening (bold/unsettling) → middle (varied) → closing (warm/hopeful)
- Uniqueness: tracks all prompts, enforces variety across subject/setting/lighting/composition
- Fallback: if LLM returns fewer prompts than markers, reuses last valid prompt

CLI:
    python modules/01c_image_planner.py \\
        --script projects/my_video/script.json \\
        --channel config/channels/history.json \\
        [--preset high] \\
        [--planner-prompt prompts/image_planner_v1.txt]
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
import sys
import time
from pathlib import Path
from typing import Any

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from modules.common import get_llm_preset, load_channel_config, load_env, setup_logging

log = setup_logging("image_planner")

# ─── Constants ────────────────────────────────────────────────────────────────

MARKER_SENTINEL = "__MARKER__"
DEFAULT_PRESET  = "high"        # Sonnet — sufficient for visual creativity, cheaper than Opus
DEFAULT_PLANNER_PROMPT = ROOT / "prompts" / "image_planner_v1.txt"
CONTEXT_WORDS   = 40            # words of narration before/after each marker for context window
VOIDAI_BASE     = "https://api.voidai.app/v1"


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _load_script(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def _save_script(path: Path, data: dict[str, Any]) -> None:
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    log.info("Saved: %s", path)


def _count_markers(script: dict[str, Any]) -> int:
    return sum(
        p == MARKER_SENTINEL
        for b in script.get("blocks", [])
        for p in (b.get("image_prompts") or [])
    )


def _build_context_prompt(
    script: dict[str, Any],
    image_style: str,
    planner_system: str,
) -> tuple[str, str]:
    """
    Build (system_prompt, user_message) for the Art Director LLM call.

    The user message contains:
    - Video title + topic
    - Full narration of all blocks with [MARKER N] positions visible
    - Total marker count
    - Image style string
    """
    title  = script.get("title", "Untitled")
    niche  = script.get("niche", "psychology/history")
    blocks = script.get("blocks", [])

    # Build annotated narration: replace marker positions with [MARKER N] labels
    lines: list[str] = []
    marker_idx = 0
    cumulative_words = 0

    for block in blocks:
        btype  = block.get("type", "section")
        btitle = block.get("title", "")
        narr   = block.get("narration") or ""
        prompts = block.get("image_prompts") or []
        offsets = block.get("image_word_offsets") or []

        lines.append(f"\n--- [{btype.upper()}] {btitle} ---")

        # Split narration into words and re-insert MARKER labels at the right offsets
        words = narr.split()
        # Build a set of word positions (relative to block start) where markers fall
        marker_positions: list[tuple[int, int]] = []  # (block_word_offset, global_marker_idx)
        for i, (prompt, offset) in enumerate(zip(prompts, offsets)):
            if prompt == MARKER_SENTINEL:
                marker_positions.append((offset, marker_idx))
                marker_idx += 1

        # Reconstruct narration with marker labels interleaved
        output_words: list[str] = []
        mp_idx = 0
        for wi, word in enumerate(words):
            # Insert any markers whose offset <= current word index
            while mp_idx < len(marker_positions) and marker_positions[mp_idx][0] <= wi:
                _, gidx = marker_positions[mp_idx]
                ts_sec = int((cumulative_words + wi) / 2.5)  # ~150wpm → 2.5 words/sec
                output_words.append(f"\n[MARKER {gidx + 1}] (~{ts_sec//60}m{ts_sec%60:02d}s)\n")
                mp_idx += 1
            output_words.append(word)
        # Flush any remaining markers after last word
        while mp_idx < len(marker_positions):
            _, gidx = marker_positions[mp_idx]
            output_words.append(f"\n[MARKER {gidx + 1}]\n")
            mp_idx += 1

        lines.append(" ".join(output_words))
        cumulative_words += len(words)

    total_markers = marker_idx
    annotated_script = "\n".join(lines)

    system_prompt = planner_system.strip()

    user_message = f"""VIDEO TITLE: {title}
NICHE/TOPIC: {niche}
TOTAL MARKERS: {total_markers}
IMAGE STYLE (append to EVERY prompt): {image_style}

FULL SCRIPT WITH MARKER POSITIONS:
{annotated_script}

---
Now write exactly {total_markers} image prompts — one per [MARKER N] in order.
Output ONLY a valid JSON array of {total_markers} strings. No other text.
"""

    return system_prompt, user_message


def _parse_response(text: str, expected: int) -> list[str]:
    """Extract JSON array of strings from LLM response."""
    text = text.strip()

    # Try to find a JSON array in the response
    # Remove markdown fences if present
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"```\s*$", "", text, flags=re.MULTILINE)
    text = text.strip()

    # Try direct parse
    try:
        result = json.loads(text)
        if isinstance(result, list):
            return [str(p).strip() for p in result]
    except json.JSONDecodeError:
        pass

    # Try to find array with regex
    m = re.search(r"\[[\s\S]*\]", text)
    if m:
        try:
            result = json.loads(m.group(0))
            if isinstance(result, list):
                return [str(p).strip() for p in result]
        except json.JSONDecodeError:
            pass

    # Fallback: split by numbered lines
    lines = [l.strip().strip('"').strip(",") for l in text.splitlines() if l.strip()]
    prompts = [l for l in lines if len(l) > 20]
    if prompts:
        log.warning("JSON parse failed — extracted %d lines as fallback", len(prompts))
        return prompts

    log.error("Could not parse LLM response as prompt list")
    return []


async def _call_llm(
    system_prompt: str,
    user_message: str,
    preset: dict[str, Any],
    expected_prompts: int,
) -> list[str]:
    """Call VoidAI and return list of image prompt strings."""
    import httpx

    load_env()
    import os
    api_key = os.environ.get("VOIDAI_API_KEY", "")
    model   = preset.get("model", "claude-sonnet-4-5-20250929")

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type":  "application/json",
    }

    payload = {
        "model": model,
        "max_tokens": max(4096, expected_prompts * 120),  # ~120 tokens per prompt
        "messages": [
            {"role": "user", "content": user_message},
        ],
        "system": system_prompt,
    }

    log.info("Calling Art Director LLM: model=%s  markers=%d", model, expected_prompts)
    t0 = time.monotonic()

    async with httpx.AsyncClient(timeout=300) as client:
        resp = await client.post(f"{VOIDAI_BASE}/chat/completions", headers=headers, json=payload)
        resp.raise_for_status()

    elapsed = time.monotonic() - t0
    data = resp.json()
    content = data["choices"][0]["message"]["content"]

    usage = data.get("usage", {})
    log.info(
        "Art Director done in %.1fs — in=%d out=%d tokens",
        elapsed,
        usage.get("prompt_tokens", 0),
        usage.get("completion_tokens", 0),
    )

    prompts = _parse_response(content, expected_prompts)
    log.info("Parsed %d prompts (expected %d)", len(prompts), expected_prompts)
    return prompts


def _apply_prompts(script: dict[str, Any], prompts: list[str]) -> dict[str, Any]:
    """
    Replace MARKER_SENTINEL entries in script.image_prompts with actual prompts.
    Returns modified script dict.
    """
    prompt_iter = iter(prompts)
    last_valid  = ""
    replaced    = 0

    for block in script.get("blocks", []):
        image_prompts = block.get("image_prompts") or []
        new_prompts: list[str] = []

        for p in image_prompts:
            if p == MARKER_SENTINEL:
                try:
                    actual = next(prompt_iter)
                    if actual:
                        last_valid = actual
                    new_prompts.append(last_valid or "dramatic historical scene, oil painting style")
                    replaced += 1
                except StopIteration:
                    # Fewer prompts than markers — reuse last
                    log.warning("Ran out of prompts — reusing last for remaining markers")
                    new_prompts.append(last_valid or "dramatic historical scene, oil painting style")
                    replaced += 1
            else:
                new_prompts.append(p)

        block["image_prompts"]  = new_prompts
        block["image_prompt"]   = new_prompts[0] if new_prompts else ""

    log.info("Applied %d prompts to script", replaced)
    return script


# ─── Public API ───────────────────────────────────────────────────────────────

async def plan_images(
    script_path: Path,
    channel_config: dict[str, Any],
    *,
    preset_name: str = DEFAULT_PRESET,
    planner_prompt_path: Path | None = None,
    image_style: str = "",
    progress_callback: Any | None = None,
) -> dict[str, Any]:
    """
    Main entry point for the image planning step.

    Reads script.json, generates structured image prompts for all __MARKER__ positions,
    writes the updated script back to disk, and returns the updated script dict.

    Args:
        script_path:         Path to script.json (modified in-place).
        channel_config:      Loaded channel config dict.
        preset_name:         LLM quality preset (default: 'high' = Sonnet).
        planner_prompt_path: Override path to image_planner system prompt.
        image_style:         Image generation style string to append to every prompt.
        progress_callback:   Optional callable({type, step, message}) for progress events.
    """
    def _emit(msg: str, pct: float = 0.0) -> None:
        if progress_callback:
            try:
                progress_callback({"type": "sub_progress", "step": "1c", "pct": pct, "message": msg})
            except Exception:
                pass
        log.info(msg)

    script = _load_script(script_path)
    total_markers = _count_markers(script)

    if total_markers == 0:
        log.info("No __MARKER__ sentinels found — script already has real prompts, skipping.")
        return script

    _emit(f"Art Director: planning {total_markers} image prompts…", 0.0)

    # Load planner system prompt
    prompt_file = planner_prompt_path or DEFAULT_PLANNER_PROMPT
    if not prompt_file.exists():
        raise FileNotFoundError(f"Image planner prompt not found: {prompt_file}")
    planner_system = prompt_file.read_text(encoding="utf-8")

    # Determine image style
    style = image_style or channel_config.get("image_style", "")

    # Get LLM preset
    preset = get_llm_preset(channel_config, preset_name)

    # Build prompt
    system_prompt, user_message = _build_context_prompt(script, style, planner_system)

    # Call LLM
    _emit(f"Art Director: calling {preset.get('model','?')} for {total_markers} prompts…", 10.0)
    prompts = await _call_llm(system_prompt, user_message, preset, total_markers)

    if not prompts:
        raise RuntimeError("Art Director LLM returned no prompts — cannot continue")

    if len(prompts) < total_markers:
        log.warning(
            "Art Director returned %d prompts but expected %d — will reuse last for remainder",
            len(prompts), total_markers,
        )

    # Apply prompts to script
    _emit(f"Art Director: applying {len(prompts)} prompts to script…", 90.0)
    script = _apply_prompts(script, prompts)

    # Save updated script
    _save_script(script_path, script)
    _emit(f"Art Director: done — {total_markers} markers replaced with real prompts.", 100.0)

    return script


# ─── CLI ──────────────────────────────────────────────────────────────────────

async def _main() -> None:
    parser = argparse.ArgumentParser(description="VideoForge — Image Planner (Art Director pass)")
    parser.add_argument("--script",  required=True, help="Path to script.json")
    parser.add_argument("--channel", default="config/channels/history.json", help="Channel config JSON")
    parser.add_argument("--preset",  default=DEFAULT_PRESET, help="LLM preset (max/high/balanced/bulk/test)")
    parser.add_argument("--planner-prompt", default=None, help="Override image planner system prompt path")
    parser.add_argument("--image-style",    default="", help="Override image style string")
    args = parser.parse_args()

    load_env()
    channel_config = load_channel_config(args.channel)
    script_path    = Path(args.script)
    prompt_path    = Path(args.planner_prompt) if args.planner_prompt else None

    await plan_images(
        script_path,
        channel_config,
        preset_name=args.preset,
        planner_prompt_path=prompt_path,
        image_style=args.image_style or "",
    )


if __name__ == "__main__":
    asyncio.run(_main())
