"""
VideoForge — Module 07: Metadata Generator.

script.json + audio_duration → metadata.json (YouTube-ready).

Generates:
  - SEO-optimized title (≤ 60 chars, high CTR)
  - Description: hook + summary + timestamps + CTA + hashtags
  - Tags: 15–25 relevant keywords

Timestamps are computed from cumulative block audio_duration values.
All text generated by VoidAI (model from channel config LLM preset,
default: metadata = gpt-4.1-mini).

CLI:
    python modules/07_metadata_generator.py \\
        --script projects/my_video/script.json \\
        --channel config/channels/history.json

    python modules/07_metadata_generator.py \\
        --script projects/my_video/script.json \\
        --channel config/channels/history.json \\
        --preset balanced --dry-run
"""

import asyncio
import json
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from clients.voidai_client import VoidAIClient
from modules.common import (
    get_llm_preset,
    load_channel_config,
    load_env,
    setup_logging,
)

log = setup_logging("metadata_gen")

# ─── Constants ────────────────────────────────────────────────────────────────

METADATA_FILENAME    = "metadata.json"
DEFAULT_CATEGORY_ID  = "27"          # YouTube: Education
MAX_TITLE_LEN        = 60            # YouTube title limit (best practice)
MAX_TAGS             = 25
EXCERPT_MAX_CHARS    = 120           # Narration excerpt per block in prompt
DEFAULT_META_MODEL   = "gpt-4.1-mini"

_SYSTEM_PROMPT = """\
You are an expert YouTube SEO specialist. Generate metadata that maximizes \
click-through rate, watch time, and discoverability.
Respond ONLY with a valid JSON object — no markdown, no explanation."""

_USER_TEMPLATE = """\
Generate YouTube metadata for a {niche} channel video.

Channel: {channel_name}
Language: {language}
Original script title: {title}
Existing tags hint: {tags_hint}

Script outline:
{outline}

Requirements:
1. title — max {max_title_len} characters, high CTR, include a power word or \
number where natural, do NOT just copy the script title
2. description — 180-300 words structured as:
   • Hook sentence (do NOT repeat the title literally)
   • 2-3 sentence content summary
   • Empty line then "📌 TIMESTAMPS:" followed by the timestamps below
   • CTA ("Like & subscribe for more {niche} content.")
   • 3-5 relevant hashtags on the last line (e.g. #History #Ancient)
3. tags — list of 15-25 tags (mix short keywords + long-tail phrases, \
all lowercase, no # symbol)

Timestamps to embed verbatim in the description:
{timestamps_block}

Reply with JSON only (no markdown fences):
{{"title": "...", "description": "...", "tags": ["tag1", "tag2", ...]}}"""


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _fmt_timestamp(seconds: float) -> str:
    """Format seconds as M:SS (e.g. 75.3 → '1:15')."""
    total = int(seconds)
    m, s = divmod(total, 60)
    return f"{m}:{s:02d}"


def _build_timestamps(blocks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """
    Compute cumulative timestamps from blocks with audio_duration.

    Returns list of {"time": "M:SS", "label": "..."} dicts.
    Skips blocks without narration (e.g. silent CTA filler blocks).
    """
    result: list[dict[str, Any]] = []
    cursor = 0.0

    for block in blocks:
        dur = block.get("audio_duration") or 0.0
        narration = (block.get("narration") or "").strip()
        label = (block.get("timestamp_label") or block.get("id", "")).strip()

        if narration and label:
            result.append({"time": _fmt_timestamp(cursor), "label": label})

        cursor += dur

    return result


def _build_outline(blocks: list[dict[str, Any]]) -> str:
    """Build a compact script outline string for the LLM prompt."""
    lines: list[str] = []
    cursor = 0.0

    for block in blocks:
        dur   = block.get("audio_duration") or 0.0
        label = (block.get("timestamp_label") or block.get("id", "")).strip()
        btype = block.get("type", "content")
        narr  = (block.get("narration") or "").strip()

        if not narr:
            cursor += dur
            continue

        excerpt = narr[:EXCERPT_MAX_CHARS].replace("\n", " ")
        if len(narr) > EXCERPT_MAX_CHARS:
            excerpt += "..."

        start_str = _fmt_timestamp(cursor)
        end_str   = _fmt_timestamp(cursor + dur)
        lines.append(
            f"[{btype.upper()}] {label} ({start_str}–{end_str})\n"
            f'  "{excerpt}"'
        )
        cursor += dur

    return "\n\n".join(lines) if lines else "(no blocks with narration)"


def _timestamps_block(timestamps: list[dict[str, Any]]) -> str:
    """Format timestamps as a plain-text block for embedding in description."""
    return "\n".join(f"{ts['time']} {ts['label']}" for ts in timestamps)


def _parse_llm_response(raw: str) -> dict[str, Any]:
    """Parse JSON from LLM response, stripping markdown fences if present."""
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        lines = cleaned.split("\n")
        cleaned = "\n".join(lines[1:-1]) if len(lines) > 2 else cleaned
    return json.loads(cleaned)


# ─── Core ─────────────────────────────────────────────────────────────────────

async def _generate_seo(
    script:          dict[str, Any],
    channel_config:  dict[str, Any],
    timestamps:      list[dict[str, Any]],
    meta_model:      str,
) -> dict[str, str | list[str]]:
    """
    Call VoidAI to generate SEO title, description, and tags.

    Returns dict with keys: title, description, tags.
    """
    niche        = channel_config.get("niche", "educational")
    channel_name = channel_config.get("channel_name", "")
    language     = channel_config.get("language", "en")
    orig_title   = script.get("title", "Untitled")
    existing_tags = script.get("tags", [])
    blocks        = script.get("blocks", [])

    outline          = _build_outline(blocks)
    timestamps_text  = _timestamps_block(timestamps)
    tags_hint        = ", ".join(existing_tags[:10]) if existing_tags else "(none)"

    user_prompt = _USER_TEMPLATE.format(
        niche=niche,
        channel_name=channel_name,
        language=language,
        title=orig_title,
        tags_hint=tags_hint,
        outline=outline,
        max_title_len=MAX_TITLE_LEN,
        timestamps_block=timestamps_text or "(no timestamps — audio_duration not set)",
    )

    async with VoidAIClient() as voidai:
        raw = await voidai.chat_completion(
            model=meta_model,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user",   "content": user_prompt},
            ],
            max_tokens=800,
            temperature=0.5,
        )

    try:
        data = _parse_llm_response(raw)
    except (json.JSONDecodeError, ValueError) as exc:
        log.warning("JSON parse failed: %s | raw=%s", exc, raw[:300])
        # Fallback: return raw as description, keep original title/tags
        data = {
            "title":       orig_title,
            "description": raw.strip(),
            "tags":        existing_tags,
        }

    # Enforce title length limit
    title = str(data.get("title", orig_title))
    if len(title) > MAX_TITLE_LEN:
        title = title[:MAX_TITLE_LEN - 1].rstrip() + "…"
        log.warning("Title truncated to %d chars", MAX_TITLE_LEN)

    # Enforce tags cap
    tags: list[str] = data.get("tags", existing_tags)  # type: ignore[assignment]
    if isinstance(tags, list):
        tags = [str(t).lower().strip() for t in tags[:MAX_TAGS]]
    else:
        tags = existing_tags

    return {
        "title":       title,
        "description": str(data.get("description", "")),
        "tags":        tags,
    }


# ─── Main ─────────────────────────────────────────────────────────────────────

async def generate_metadata(
    script_path:         str | Path,
    channel_config_path: str | Path,
    *,
    output_path:         str | Path | None = None,
    preset:              str | None = None,
    category_id:         str = DEFAULT_CATEGORY_ID,
    dry_run:             bool = False,
) -> Path:
    """
    Generate YouTube metadata from script.json.

    Args:
        script_path: Path to script.json (with audio_duration per block).
        channel_config_path: Path to channel config JSON.
        output_path: Where to save metadata.json. Default: script.parent/output/metadata.json.
        preset: LLM preset name (max/high/balanced/bulk/test).
        category_id: YouTube category ID (default "27" = Education).
        dry_run: Compute timestamps and show plan without calling VoidAI.

    Returns:
        Path to saved metadata.json.

    Raises:
        FileNotFoundError: If script.json not found.
    """
    load_env()

    script_path = Path(script_path)
    if not script_path.exists():
        raise FileNotFoundError(f"script.json not found: {script_path}")

    script         = json.loads(script_path.read_text(encoding="utf-8"))
    channel_config = load_channel_config(channel_config_path)
    base_dir       = script_path.parent
    out_dir        = base_dir / "output"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = Path(output_path) if output_path else out_dir / METADATA_FILENAME

    # Resolve metadata LLM model
    llm_preset  = get_llm_preset(channel_config, preset)
    meta_model  = llm_preset.get("metadata", DEFAULT_META_MODEL)

    blocks     = script.get("blocks", [])
    timestamps = _build_timestamps(blocks)

    total_dur = sum(b.get("audio_duration") or 0.0 for b in blocks)
    voiced    = sum(1 for b in blocks if (b.get("narration") or "").strip())

    log.info(
        "Script: '%s' | %d blocks (%d voiced) | total=%.1fs | model=%s",
        script.get("title", "?"), len(blocks), voiced, total_dur, meta_model,
    )
    log.info("Timestamps computed: %d entries", len(timestamps))

    if dry_run:
        log.info("[DRY RUN] Output: %s", out_path)
        log.info("[DRY RUN] Model: %s | Category: %s", meta_model, category_id)
        for ts in timestamps:
            log.info("[DRY RUN]   %s  %s", ts["time"], ts["label"])
        return out_path

    t0 = time.monotonic()
    seo = await _generate_seo(script, channel_config, timestamps, meta_model)
    elapsed = time.monotonic() - t0

    metadata: dict[str, Any] = {
        "title":        seo["title"],
        "description":  seo["description"],
        "tags":         seo["tags"],
        "category_id":  category_id,
        "language":     script.get("language", channel_config.get("language", "en")),
        "timestamps":   timestamps,
        "total_duration_seconds": round(total_dur, 2),
        "script_title": script.get("title", ""),
        "generated_by": "VideoForge",
    }

    out_path.write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")

    log.info(
        "Done: %s | title=%d chars | tags=%d | %.1fs",
        out_path.name, len(seo["title"]), len(seo["tags"]), elapsed,
    )
    log.info("Title: %s", seo["title"])
    return out_path


# ─── CLI ──────────────────────────────────────────────────────────────────────

def _main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description="VideoForge — Metadata Generator (Module 07)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python modules/07_metadata_generator.py \\
      --script projects/my_video/script.json \\
      --channel config/channels/history.json

  # Cheaper model, dry run:
  python modules/07_metadata_generator.py \\
      --script projects/my_video/script.json \\
      --channel config/channels/history.json \\
      --preset balanced --dry-run

  # Custom YouTube category (28 = Science & Technology):
  python modules/07_metadata_generator.py \\
      --script projects/my_video/script.json \\
      --channel config/channels/history.json \\
      --category-id 28
        """,
    )

    parser.add_argument("--script",  required=True, help="Path to script.json")
    parser.add_argument("--channel", required=True, help="Channel config JSON path")
    parser.add_argument(
        "--output", default=None,
        help="Output path for metadata.json (default: output/metadata.json)",
    )
    parser.add_argument(
        "--preset", default=None,
        help="LLM preset (max/high/balanced/bulk/test)",
    )
    parser.add_argument(
        "--category-id", default=DEFAULT_CATEGORY_ID,
        help=f"YouTube category ID (default: {DEFAULT_CATEGORY_ID} = Education)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Compute timestamps and show plan without calling VoidAI",
    )

    args = parser.parse_args()

    out = asyncio.run(generate_metadata(
        script_path=args.script,
        channel_config_path=args.channel,
        output_path=args.output,
        preset=args.preset,
        category_id=args.category_id,
        dry_run=args.dry_run,
    ))

    if not args.dry_run:
        log.info("Metadata saved: %s", out)


if __name__ == "__main__":
    _main()
