"""
VideoForge — Module 08b: YouTube A/B Test Prep.

Generates 3 thumbnail + title variants for YouTube's "Test & Compare" feature.

Flow:
  1. Reads title_variants (3 titles) from output/metadata.json (generated by module 07)
  2. Generates 3 thumbnail variants via WaveSpeed (same base prompt, 3 style angles)
  3. Saves thumbnails to output/ab_test/thumbnail_A.png, _B.png, _C.png
  4. Sets thumbnail_A on the already-uploaded video (via YouTube API)
  5. Prints step-by-step instructions to add thumbnails B & C in YouTube Studio

YouTube "Test & Compare" limitations (API):
  - Only 1 thumbnail can be set via API (thumbnails.set)
  - Adding 2nd and 3rd thumbnails for A/B test requires YouTube Studio UI
  - Title A/B test also requires YouTube Studio UI
  - This module automates everything that CAN be automated

Thumbnail style variants:
  A (primary): Original prompt — dramatic, high-contrast, cinematic
  B: Same subject + bright/clean/minimalist — different visual energy
  C: Same subject + close-up/emotional/text space — max emotion angle

CLI:
    python modules/08b_ab_test.py \\
        --script projects/my_video/script.json \\
        --channel config/channels/history.json \\
        --channel-name main

    python modules/08b_ab_test.py \\
        --script projects/my_video/script.json \\
        --channel config/channels/history.json \\
        --channel-name main \\
        --no-upload          # skip setting thumbnail_A via API
        --dry-run            # generate thumbnails only, no API calls
"""

from __future__ import annotations

import argparse
import asyncio
import json
import random
import shutil
import sys
import webbrowser
from pathlib import Path
from typing import Any

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from clients.wavespeed_client import WaveSpeedClient
from clients.youtube_auth import get_youtube_service_from_config
from modules.common import load_channel_config, load_env, setup_logging
from googleapiclient.http import MediaFileUpload

log = setup_logging("ab_test")

# ─── Constants ────────────────────────────────────────────────────────────────

AB_DIR          = "ab_test"
THUMBNAIL_SIZE  = "1280*720"
FIXED_SEED_A    = 42
MIN_FILE_BYTES  = 10_000

# Style suffixes appended to the base prompt for each variant
_STYLE_SUFFIX: dict[str, str] = {
    "A": (
        ", dramatic cinematic lighting, dark background, high contrast, "
        "professional YouTube thumbnail composition, rule of thirds"
    ),
    "B": (
        ", bright vivid colors, clean minimalist background, bold graphic style, "
        "eye-catching contrast, modern flat design, professional YouTube thumbnail"
    ),
    "C": (
        ", extreme close-up emotional expression, warm golden tones, "
        "space for text overlay at top, cinematic shallow depth of field, "
        "powerful YouTube thumbnail"
    ),
}


# ─── Thumbnail generation ─────────────────────────────────────────────────────

async def _generate_one(
    wave: WaveSpeedClient,
    prompt: str,
    out_path: Path,
    seed: int,
    variant: str,
) -> bool:
    """Generate a single thumbnail variant. Returns True on success."""
    try:
        await wave.generate_text2img(
            prompt,
            size=THUMBNAIL_SIZE,
            seed=seed,
            num_inference_steps=4,
            output_path=out_path,
        )
        if out_path.exists() and out_path.stat().st_size >= MIN_FILE_BYTES:
            log.info("Variant %s: generated (%d KB)", variant, out_path.stat().st_size // 1024)
            return True
        log.warning("Variant %s: file too small or missing", variant)
        return False
    except Exception as exc:
        log.error("Variant %s: WaveSpeed error: %s", variant, exc)
        return False


async def generate_thumbnails(
    base_prompt: str,
    ab_dir: Path,
) -> dict[str, Path]:
    """
    Generate 3 thumbnail variants (A, B, C) and save to ab_dir.

    Returns:
        dict mapping variant letter → Path (only successful variants included)
    """
    ab_dir.mkdir(parents=True, exist_ok=True)
    results: dict[str, Path] = {}

    async with WaveSpeedClient() as wave:
        tasks = {}
        for variant, suffix in _STYLE_SUFFIX.items():
            prompt = base_prompt + suffix
            out_path = ab_dir / f"thumbnail_{variant}.png"
            seed = FIXED_SEED_A if variant == "A" else random.randint(10_000, 999_999)
            log.info("Generating thumbnail %s (seed=%d)...", variant, seed)
            tasks[variant] = (wave, prompt, out_path, seed, variant)

        # Generate all 3 concurrently
        coros = {
            v: _generate_one(*args)
            for v, args in tasks.items()
        }
        done = await asyncio.gather(*coros.values(), return_exceptions=True)
        for variant, result in zip(coros.keys(), done):
            out_path = ab_dir / f"thumbnail_{variant}.png"
            if result is True and out_path.exists():
                results[variant] = out_path
            else:
                log.warning("Variant %s failed: %s", variant, result)

    return results


# ─── YouTube thumbnail update ─────────────────────────────────────────────────

def _set_thumbnail_api(
    channel_name: str,
    channel_config: dict,
    video_id: str,
    thumb_path: Path,
) -> bool:
    """Set thumbnail A on the video via YouTube API (proxy-aware)."""
    try:
        service = get_youtube_service_from_config(channel_name, channel_config)
        mime = "image/png" if thumb_path.suffix.lower() == ".png" else "image/jpeg"
        media = MediaFileUpload(str(thumb_path), mimetype=mime)
        service.thumbnails().set(videoId=video_id, media_body=media).execute()
        log.info("Thumbnail A set on video %s", video_id)
        return True
    except Exception as exc:
        log.warning("Could not set thumbnail via API (non-fatal): %s", exc)
        return False


# ─── Main ─────────────────────────────────────────────────────────────────────

async def prepare_ab_test(
    script_path:         str | Path,
    channel_config_path: str | Path,
    channel_name:        str | None = None,
    no_upload:           bool = False,
    dry_run:             bool = False,
    open_studio:         bool = True,
) -> dict[str, Any]:
    """
    Prepare A/B test assets: 3 thumbnails + 3 titles.

    Returns:
        dict with keys: video_id, titles, thumbnails (variant → path)
    """
    load_env()

    script_path = Path(script_path)
    base_dir = script_path.parent
    out_dir  = base_dir / "output"
    ab_dir   = out_dir / AB_DIR

    # ── Load script ───────────────────────────────────────────────────────────
    script = json.loads(script_path.read_text(encoding="utf-8"))
    channel_config = load_channel_config(channel_config_path)

    # Resolve channel name for OAuth
    ch_name = (
        channel_name
        or channel_config.get("channel_name", "")
        or "channel"
    ).replace(" ", "_").lower()

    # ── Load metadata (titles) ────────────────────────────────────────────────
    meta_path = out_dir / "metadata.json"
    if not meta_path.exists():
        raise FileNotFoundError(
            f"metadata.json not found: {meta_path}\n"
            "Run module 07 first: python modules/07_metadata_generator.py ..."
        )
    metadata = json.loads(meta_path.read_text(encoding="utf-8"))
    title_variants: list[str] = metadata.get("title_variants", [metadata.get("title", "?")])

    # Ensure exactly 3
    while len(title_variants) < 3:
        title_variants.append(title_variants[-1])
    title_variants = title_variants[:3]

    log.info("Titles for A/B test:")
    for i, t in enumerate(title_variants, 1):
        log.info("  %s: %s", "ABC"[i - 1], t)

    # ── Get thumbnail base prompt ─────────────────────────────────────────────
    base_prompt: str = (
        script.get("thumbnail_prompt")
        or metadata.get("thumbnail_prompt")
        or script.get("title", "")
    )
    if not base_prompt:
        raise ValueError("No thumbnail_prompt found in script.json or metadata.json")

    log.info("Base thumbnail prompt: %s", base_prompt[:80] + "..." if len(base_prompt) > 80 else base_prompt)

    # ── Get video_id from upload_result.json ──────────────────────────────────
    upload_result_path = out_dir / "upload_result.json"
    video_id: str | None = None
    if upload_result_path.exists():
        ur = json.loads(upload_result_path.read_text(encoding="utf-8"))
        video_id = ur.get("video_id")
        log.info("Video ID from upload_result.json: %s", video_id)
    else:
        log.warning("No upload_result.json found — thumbnail upload will be skipped")

    # ── Generate thumbnails ───────────────────────────────────────────────────
    if dry_run:
        log.info("[DRY RUN] Would generate 3 thumbnails in: %s", ab_dir)
        log.info("[DRY RUN] Style A: dramatic cinematic")
        log.info("[DRY RUN] Style B: bright minimalist")
        log.info("[DRY RUN] Style C: close-up emotional")
        thumbnails: dict[str, Path] = {}
    else:
        log.info("Generating 3 thumbnail variants (parallel)...")
        thumbnails = await generate_thumbnails(base_prompt, ab_dir)

        # Copy A to output/thumbnail.png (main thumbnail)
        if "A" in thumbnails:
            shutil.copy2(thumbnails["A"], out_dir / "thumbnail_A.png")

    # ── Set thumbnail A on video ──────────────────────────────────────────────
    thumb_set = False
    if not dry_run and not no_upload and video_id and "A" in thumbnails:
        log.info("Setting thumbnail A on video %s...", video_id)
        thumb_set = _set_thumbnail_api(ch_name, channel_config, video_id, thumbnails["A"])

    # ── Save A/B test summary ─────────────────────────────────────────────────
    summary = {
        "video_id":       video_id,
        "video_url":      f"https://www.youtube.com/watch?v={video_id}" if video_id else None,
        "studio_url":     f"https://studio.youtube.com/video/{video_id}/edit" if video_id else None,
        "titles":         {letter: t for letter, t in zip("ABC", title_variants)},
        "thumbnails":     {k: str(v) for k, v in thumbnails.items()},
        "thumbnail_A_set_via_api": thumb_set,
    }

    summary_path = out_dir / "ab_test_summary.json"
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    log.info("Summary saved: %s", summary_path)

    # ── Print instructions ────────────────────────────────────────────────────
    _print_instructions(summary, thumbnails, title_variants, video_id, open_studio)

    return summary


def _print_instructions(
    summary:        dict,
    thumbnails:     dict[str, Path],
    titles:         list[str],
    video_id:       str | None,
    open_studio:    bool,
) -> None:
    # Use UTF-8 stdout to avoid cp1252 UnicodeEncodeError on Windows
    import io
    out = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

    studio_url = summary.get("studio_url", "")

    out.write("\n" + "=" * 65 + "\n")
    out.write("  [AB-TEST]  YouTube A/B Test -- ready\n")
    out.write("=" * 65 + "\n")

    out.write("\n[TITLES] 3 variants:\n")
    for letter, title in zip("ABC", titles):
        marker = "  <-- active" if letter == "A" else ""
        out.write(f"  {letter}: {title}{marker}\n")

    out.write(f"\n[THUMBNAILS] saved to output/ab_test/\n")
    for letter, path in thumbnails.items():
        size_kb = path.stat().st_size // 1024 if path.exists() else 0
        out.write(f"  {letter}: {path.name}  ({size_kb} KB)\n")

    if video_id:
        out.write(f"\n[VIDEO] https://www.youtube.com/watch?v={video_id}\n")
        out.write(f"[STUDIO] {studio_url}\n")
        out.write(f"\n[INSTRUCTIONS] Test & Compare in YouTube Studio:\n")
        out.write(f"  1. Open: {studio_url}\n")
        out.write(f"  2. Go to 'Analytics' -> 'Experiments' tab (or Details -> More options)\n")
        out.write(f"  3. Click '+ Create experiment'\n")
        out.write(f"  4. Add thumbnail B: {thumbnails.get('B', 'thumbnail_B.png')}\n")
        out.write(f"  5. Add thumbnail C: {thumbnails.get('C', 'thumbnail_C.png')}\n")
        out.write(f"  6. For title A/B: Details -> Title -> 'Test a title'\n")
        out.write(f"     Variant B: {titles[1] if len(titles) > 1 else '-'}\n")
        out.write(f"     Variant C: {titles[2] if len(titles) > 2 else '-'}\n")
        out.write(f"  7. Click 'Start experiment' -- YouTube splits traffic automatically\n")

    out.write("\n" + "=" * 65 + "\n\n")
    out.flush()

    if open_studio and studio_url:
        try:
            webbrowser.open(studio_url)
            log.info("YouTube Studio відкрито в браузері")
        except Exception:
            pass


# ─── CLI ──────────────────────────────────────────────────────────────────────

def _main() -> None:
    parser = argparse.ArgumentParser(
        description="VideoForge — YouTube A/B Test Prep (Module 08b)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python modules/08b_ab_test.py \\
      --script projects/my_video/script.json \\
      --channel config/channels/history.json \\
      --channel-name main

  python modules/08b_ab_test.py \\
      --script projects/my_video/script.json \\
      --channel config/channels/history.json \\
      --channel-name main --dry-run
""",
    )
    parser.add_argument("--script",       required=True, help="Path to script.json")
    parser.add_argument("--channel",      required=True, help="Channel config JSON path")
    parser.add_argument("--channel-name", default=None,
                        help="OAuth2 channel name (e.g. 'main'). Defaults from channel config.")
    parser.add_argument("--no-upload",    action="store_true",
                        help="Skip setting thumbnail A via YouTube API")
    parser.add_argument("--no-browser",   action="store_true",
                        help="Don't open YouTube Studio in browser")
    parser.add_argument("--dry-run",      action="store_true",
                        help="Show plan without generating images or API calls")
    args = parser.parse_args()

    asyncio.run(prepare_ab_test(
        script_path=args.script,
        channel_config_path=args.channel,
        channel_name=args.channel_name,
        no_upload=args.no_upload,
        dry_run=args.dry_run,
        open_studio=not args.no_browser,
    ))


if __name__ == "__main__":
    _main()
